"""Regenerate reference documents from live system state.

Generates system-landscape.md, neo4j-schema.md, and playbook-index.md
from manifest.json, Neo4j schema queries, and playbook frontmatter.
Validates (but does not overwrite) research-standards.md.

Designed as in-process tool (_impl function) for fast dispatch.
---
description: Generate reference docs from manifest, Neo4j schema, playbooks
creates_nodes: []
creates_edges: []
databases: [corcoran, lifestream]
read_only: true
---
"""
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

from lib.paths import CLAUDE_FILES, ensure_dir
from lib.db import GRAPH_DATABASE, ENTRY_DATABASE

REFERENCES_DIR = CLAUDE_FILES / "references"

# -- Domain-Specific Paths ----------------------------------------------------
# These paths control where sync_system_docs looks for source data.
# Override via environment variables for different deployment layouts.
#
# NICKTOOLS_MANIFEST:        Path to manifest.json (tool registry)
# NICKTOOLS_PLAYBOOKS_DIR:   Directory containing playbook .md files
# NICKTOOLS_STANDARDS_PATH:  Path to research-standards.md (validated, not overwritten)

MANIFEST_PATH = Path(os.getenv(
    "NICKTOOLS_MANIFEST",
    str(CLAUDE_FILES / "scripts" / "nicktools_mcp" / "manifest.json")
))
PLAYBOOKS_DIR = Path(os.getenv(
    "NICKTOOLS_PLAYBOOKS_DIR",
    str(CLAUDE_FILES / "playbooks")
))
RESEARCH_STANDARDS_PATH = Path(os.getenv(
    "NICKTOOLS_STANDARDS_PATH",
    str(REFERENCES_DIR / "research-standards.md")
))

# Extra routing table entries for system-landscape.md (task, environment, tool).
# These appear after nicktools operations in the routing table.
# Override or extend for your deployment's non-nicktools tools.
EXTRA_ROUTES = [
    ("Neo4j read queries", "Neo4j MCP", "`mcp__graph__read-cypher` / `mcp__entries__read-cypher`"),
    ("Neo4j write queries", "Neo4j MCP", "`mcp__graph__write-cypher` / `mcp__entries__write-cypher`"),
    ("Quick factual lookup", "Cowork VM", "`WebSearch`"),
    ("Read public page", "Cowork VM", "`WebFetch`"),
    ("File editing", "Cowork VM", "Read/Write/Edit"),
]


def sync_system_docs_impl(sections=None, driver=None, **kwargs):
    """Regenerate reference documents from live system state.

    Args:
        sections: Optional list of sections to regenerate. Default: all.
                  Valid: ["landscape", "schema", "playbooks", "standards"]
        driver: Shared Neo4j driver (injected by dispatcher)

    Returns:
        Summary dict: which docs regenerated, what changed, warnings.
    """
    ensure_dir(REFERENCES_DIR, "reference docs directory")

    all_sections = ["landscape", "schema", "playbooks", "standards"]
    targets = sections if sections else all_sections

    results = {}
    warnings = []

    if "landscape" in targets:
        results["system-landscape.md"] = _gen_system_landscape(driver)

    if "schema" in targets:
        results["neo4j-schema.md"] = _gen_neo4j_schema(driver)

    if "playbooks" in targets:
        results["playbook-index.md"] = _gen_playbook_index(driver=driver)

    if "standards" in targets:
        validation = _validate_research_standards()
        results["research-standards.md"] = validation
        if validation.get("warnings"):
            warnings.extend(validation["warnings"])

    return {
        "status": "ok",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "sections": results,
        "warnings": warnings,
    }


# -- Generator: system-landscape.md --

def _gen_system_landscape(driver):
    """Generate system-landscape.md from manifest.json + Neo4j queries."""
    manifest = _load_manifest()
    if not manifest:
        return {"status": "error", "error": "manifest.json not found -- run core('registry_sync') first"}

    lines = [
        "# System Landscape",
        "",
        f"*Auto-generated by `sync_system_docs` -- {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        f"*Source: manifest.json (server v{manifest.get('server_version', '?')})*",
        "",
    ]

    # -- Tool Inventory --
    lines.append("## Tool Inventory")
    lines.append("")

    total_ops = 0
    for group_name, group_data in sorted(manifest.get("groups", {}).items()):
        ops = group_data.get("operations", {})
        count = len(ops)
        total_ops += count
        lines.append(f"### {group_name} -- {count} operations")
        lines.append("")

        for op_name, op_data in sorted(ops.items()):
            desc = op_data.get("description", "")
            params = op_data.get("params", [])
            required = [p["name"] for p in params if p.get("required")]
            optional = [p["name"] for p in params if not p.get("required")
                        and p["name"] not in ("database",)]

            sig = ", ".join(required) if required else ""
            opt_str = f" [optional: {', '.join(optional)}]" if optional else ""
            dispatch = op_data.get("dispatch", "?")

            lines.append(f"- **`{op_name}({sig})`**{opt_str}")
            if desc:
                lines.append(f"  {desc} ({dispatch})")
        lines.append("")

    lines.append(f"**Total: {total_ops} operations across {len(manifest.get('groups', {}))} groups**")
    lines.append("")

    # -- Routing Table --
    lines.append("## Routing Table")
    lines.append("")
    lines.append("| Task | Environment | Tool |")
    lines.append("|------|-------------|------|")

    # nicktools operations from manifest
    for group_name, group_data in sorted(manifest.get("groups", {}).items()):
        for op_name in sorted(group_data.get("operations", {}).keys()):
            lines.append(f"| {op_name} | nicktools | `{group_name}(\"{op_name}\", params)` |")

    # Non-nicktools routes -- extend EXTRA_ROUTES to add deployment-specific entries
    for task, env, tool in EXTRA_ROUTES:
        lines.append(f"| {task} | {env} | {tool} |")
    lines.append("")

    # -- Domain Taxonomy --
    domains = _query_domains(driver)
    lines.append("## Domain Taxonomy")
    lines.append("")
    if domains:
        lines.append(f"**{len(domains)} canonical domains:** {', '.join(domains)}")
    else:
        lines.append("*(Could not query domains -- Neo4j may be unavailable)*")
    lines.append("")

    # -- Entry Types --
    entry_types = _query_entry_types(driver)
    lines.append("## Entry Types")
    lines.append("")
    if entry_types:
        lines.append("| Type | Count |")
        lines.append("|------|-------|")
        for et in entry_types:
            lines.append(f"| {et['type']} | {et['count']} |")
    else:
        lines.append("*(Could not query entry types -- Neo4j may be unavailable)*")
    lines.append("")

    # -- Library Modules --
    lines.append("## Library Modules")
    lines.append("")
    lib_dir = CLAUDE_FILES / "scripts" / "nicktools_mcp" / "lib"
    if lib_dir.exists():
        modules = sorted(f.name for f in lib_dir.glob("*.py") if f.name != "__init__.py" and not f.name.startswith("_"))
        lines.append(f"**{len(modules)} modules in lib/:** {', '.join(modules)}")
    lines.append("")

    content = "\n".join(lines)
    return _write_reference("system-landscape.md", content)


# -- Generator: neo4j-schema.md --

def _gen_neo4j_schema(driver):
    """Generate neo4j-schema.md from live Neo4j schema queries.

    Also runs sync_schema_from_neo4j() to update the in-memory schema registry
    and includes a registry summary section in the output.
    """
    lines = [
        "# Neo4j Schema Reference",
        "",
        f"*Auto-generated by `sync_system_docs` -- {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
    ]

    # Run schema sync to update registry from live data
    sync_result = None
    try:
        from lib.schema import sync_schema_from_neo4j, get_sync_summary
        sync_result = sync_schema_from_neo4j(driver=driver, database=GRAPH_DATABASE)

        # Add registry sync summary section
        lines.append("## Schema Registry Sync")
        lines.append("")
        if sync_result.get("new_labels"):
            lines.append(f"**New labels discovered:** {', '.join(sync_result['new_labels'])}")
        if sync_result.get("new_rel_types"):
            lines.append(f"**New relationship types discovered:** {', '.join(sync_result['new_rel_types'])}")
        if sync_result.get("new_properties"):
            for label, props in sorted(sync_result["new_properties"].items()):
                lines.append(f"**New properties on {label}:** {', '.join(props)}")
        if not sync_result.get("new_labels") and not sync_result.get("new_rel_types") and not sync_result.get("new_properties"):
            lines.append("Registry is in sync with live schema -- no new types or properties discovered.")
        if sync_result.get("errors"):
            lines.append(f"**Sync errors:** {'; '.join(sync_result['errors'])}")
        lines.append("")

        # Add registry summary
        summary = get_sync_summary()
        lines.append(f"**Registry:** {len(summary['node_types'])} node types, "
                      f"{len(summary['rel_types'])} relationship types, "
                      f"{len(summary['role_labels'])} role labels")
        lines.append("")
    except Exception as e:
        lines.append(f"## Schema Registry Sync")
        lines.append("")
        lines.append(f"*Sync failed: {e}*")
        lines.append("")

    for db_name in [GRAPH_DATABASE, ENTRY_DATABASE]:
        lines.append(f"## {db_name}")
        lines.append("")

        # Node labels -- grouped by base label (not every label combination)
        node_data = _query_base_labels(driver, db_name)
        if node_data:
            lines.append("### Node Types")
            lines.append("")
            for label, info in sorted(node_data.items()):
                count_str = f" ({info['count']:,} nodes)" if info.get("count") else ""
                lines.append(f"**{label}**{count_str}")
                if info.get("properties"):
                    lines.append(f"Properties: {', '.join(sorted(info['properties']))}")
                if info.get("also_labeled"):
                    lines.append(f"Common additional labels: {', '.join(sorted(info['also_labeled']))}")
                lines.append("")

        # Relationship types with properties
        rel_props = _query_relationship_properties(driver, db_name)
        if rel_props:
            lines.append("### Relationship Types")
            lines.append("")
            for rel_type, props in sorted(rel_props.items()):
                prop_str = f" -- properties: {', '.join(sorted(props))}" if props else ""
                lines.append(f"- `{rel_type}`{prop_str}")
            lines.append("")

        # Indexes
        indexes = _query_indexes(driver, db_name)
        if indexes:
            lines.append("### Indexes")
            lines.append("")
            for idx in indexes:
                lines.append(f"- **{idx['name']}** ({idx['type']}): {idx['labels']} on {idx['properties']}")
            lines.append("")

        # APOC triggers (lifestream only)
        if db_name == ENTRY_DATABASE:
            triggers = _query_triggers(driver, db_name)
            if triggers:
                lines.append("### APOC Triggers")
                lines.append("")
                for t in triggers:
                    lines.append(f"- `{t}`")
                lines.append("")
            elif triggers is not None:
                lines.append("### APOC Triggers")
                lines.append("")
                lines.append("*No triggers found -- may need reinstallation after Neo4j restart.*")
                lines.append("")

    # Neo4j version info
    version_info = _query_neo4j_version(driver)
    if version_info:
        lines.append("## Neo4j Stack")
        lines.append("")
        for k, v in version_info.items():
            lines.append(f"- **{k}**: {v}")
        lines.append("")

    content = "\n".join(lines)
    return _write_reference("neo4j-schema.md", content)


# -- Generator: playbook-index.md --

def _gen_playbook_index(driver=None):
    """Generate playbook-index.md from playbook frontmatter + validation.

    Enhanced validation checks:
    - Tool references against manifest
    - lastUsed staleness (>30 days)
    - File path references in body text
    - Domain references against canonical domain list
    """
    manifest = _load_manifest()
    all_ops = set()
    if manifest:
        for group_data in manifest.get("groups", {}).values():
            all_ops.update(group_data.get("operations", {}).keys())

    # Get canonical domains for cross-reference
    canonical_domains = set()
    if driver:
        domains = _query_domains(driver)
        if domains:
            canonical_domains = set(d.lower() for d in domains)

    lines = [
        "# Playbook Index",
        "",
        f"*Auto-generated by `sync_system_docs` -- {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
    ]

    playbooks = []
    warnings = []

    if not PLAYBOOKS_DIR.exists():
        lines.append("*No playbooks directory found.*")
        content = "\n".join(lines)
        return _write_reference("playbook-index.md", content)

    today = datetime.now(timezone.utc).date()

    for pb_file in sorted(PLAYBOOKS_DIR.glob("*.md")):
        fm = _parse_playbook_frontmatter(pb_file)
        if not fm:
            warnings.append(f"{pb_file.name}: no frontmatter found")
            continue

        pb = {
            "file": pb_file.name,
            "title": fm.get("title", pb_file.stem),
            "status": fm.get("status", "unknown"),
            "created": fm.get("created", "?"),
            "lastUsed": fm.get("lastUsed", "?"),
            "domains": fm.get("domains", []),
            "tools": fm.get("tools", []),
            "tags": fm.get("tags", []),
        }

        pb["tool_warnings"] = []

        # Validate tool references
        for tool_ref in pb["tools"]:
            op_name = tool_ref.replace("tool-nicktools-", "").replace("-", "_")
            if op_name not in all_ops and not tool_ref.startswith("tool-"):
                pb["tool_warnings"].append(f"Unknown tool reference: {tool_ref}")

        # Check lastUsed staleness (>30 days)
        last_used = pb["lastUsed"]
        if last_used and last_used != "?":
            try:
                from datetime import date as date_type
                lu_date = date_type.fromisoformat(str(last_used))
                days_stale = (today - lu_date).days
                if days_stale > 30:
                    pb["tool_warnings"].append(
                        f"Stale: last used {days_stale} days ago ({last_used})"
                    )
            except (ValueError, TypeError):
                pass

        # Validate domains against canonical list
        if canonical_domains and pb["domains"]:
            for domain in pb["domains"]:
                if domain.lower() not in canonical_domains:
                    pb["tool_warnings"].append(
                        f"Unknown domain '{domain}' -- not in canonical domain list"
                    )

        # Check file path references in body text
        try:
            body_text = pb_file.read_text(encoding="utf-8")
            # Look for file path references like `ClaudeFiles/...` or `playbooks/...`
            file_refs = re.findall(r'`(ClaudeFiles/[^`]+)`', body_text)
            file_refs += re.findall(r'`(playbooks/[^`]+)`', body_text)
            for ref in file_refs:
                # Resolve relative to CLAUDE_FILES parent
                if ref.startswith("ClaudeFiles/"):
                    check_path = CLAUDE_FILES / ref.replace("ClaudeFiles/", "")
                elif ref.startswith("playbooks/"):
                    check_path = CLAUDE_FILES / ref
                else:
                    continue
                if not check_path.exists():
                    pb["tool_warnings"].append(f"Missing file reference: `{ref}`")
        except OSError:
            pass

        playbooks.append(pb)

    # Summary table
    lines.append("## Playbooks")
    lines.append("")
    lines.append("| Playbook | Status | Domains | Last Used |")
    lines.append("|----------|--------|---------|-----------|")
    for pb in playbooks:
        domains_str = ", ".join(pb["domains"]) if pb["domains"] else "--"
        stale_marker = ""
        if any("Stale:" in w for w in pb.get("tool_warnings", [])):
            stale_marker = " [!]"
        lines.append(f"| [{pb['title']}](../playbooks/{pb['file']}) | {pb['status']} | {domains_str} | {pb['lastUsed']}{stale_marker} |")
    lines.append("")

    # Detailed sections
    for pb in playbooks:
        lines.append(f"### {pb['title']}")
        lines.append(f"**File:** `playbooks/{pb['file']}`")
        lines.append(f"**Created:** {pb['created']} | **Last used:** {pb['lastUsed']} | **Status:** {pb['status']}")
        if pb["tags"]:
            lines.append(f"**Tags:** {', '.join(pb['tags'])}")
        if pb["tools"]:
            lines.append(f"**Tools referenced:** {', '.join(pb['tools'])}")
        if pb["tool_warnings"]:
            lines.append(f"**[!] Warnings:** {'; '.join(pb['tool_warnings'])}")
        lines.append("")

    # Validation summary
    all_warnings = warnings + [w for pb in playbooks for w in pb.get("tool_warnings", [])]
    if all_warnings:
        lines.append("## Validation Warnings")
        lines.append("")
        for w in all_warnings:
            lines.append(f"- {w}")
        lines.append("")

    content = "\n".join(lines)
    result = _write_reference("playbook-index.md", content)
    result["playbook_count"] = len(playbooks)
    result["validation_warnings"] = len(all_warnings)
    return result


# -- Validator: research-standards.md --

def _validate_research_standards():
    """Validate research-standards.md exists and its tool references are current."""
    if not RESEARCH_STANDARDS_PATH.exists():
        return {
            "status": "missing",
            "warnings": ["research-standards.md does not exist -- create it manually"],
        }

    content = RESEARCH_STANDARDS_PATH.read_text(encoding="utf-8")

    manifest = _load_manifest()
    all_ops = set()
    if manifest:
        for group_data in manifest.get("groups", {}).values():
            all_ops.update(group_data.get("operations", {}).keys())

    warnings = []

    # Check for tool/operation references that may be stale
    # Look for patterns like `tool_name`, `graph("operation")`, etc.
    op_refs = re.findall(r'`(\w+)\("(\w+)"', content)
    for group, op in op_refs:
        if op not in all_ops:
            warnings.append(f"research-standards.md references operation '{op}' which is not in the tool registry")

    return {
        "status": "valid" if not warnings else "has_warnings",
        "warnings": warnings,
        "line_count": len(content.split("\n")),
    }


# -- Helpers --

def _load_manifest():
    """Load manifest.json, return dict or None."""
    if not MANIFEST_PATH.exists():
        return None
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return None


def _write_reference(filename, content):
    """Write a reference doc and report whether it changed."""
    path = REFERENCES_DIR / filename
    old_content = ""
    if path.exists():
        try:
            old_content = path.read_text(encoding="utf-8")
        except OSError:
            pass

    # Strip timestamp lines for comparison (they change every run)
    def strip_timestamps(text):
        return re.sub(r'\*Auto-generated by.*?\*', '', text)

    changed = strip_timestamps(old_content) != strip_timestamps(content)

    path.write_text(content, encoding="utf-8")

    return {
        "status": "updated" if changed else "unchanged",
        "path": str(path),
        "lines": len(content.split("\n")),
    }


def _parse_playbook_frontmatter(filepath):
    """Parse YAML-like frontmatter from a markdown file."""
    try:
        text = filepath.read_text(encoding="utf-8")
    except OSError:
        return None

    match = re.match(r'^---\s*\n(.*?)\n---', text, re.DOTALL)
    if not match:
        return None

    fm = {}
    for line in match.group(1).strip().split("\n"):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key = key.strip()
        value = value.strip().strip('"').strip("'")

        # Handle YAML-like lists: [a, b, c]
        if value.startswith("[") and value.endswith("]"):
            items = [v.strip().strip('"').strip("'") for v in value[1:-1].split(",")]
            fm[key] = [i for i in items if i]
        else:
            fm[key] = value

    return fm


def _query_domains(driver):
    """Query canonical domain list from lifestream database."""
    if not driver:
        return None
    try:
        with driver.session(database=ENTRY_DATABASE) as session:
            result = session.run("MATCH (d:Domain) RETURN d.name AS name ORDER BY d.name")
            return [r["name"] for r in result]
    except Exception:
        return None


def _query_entry_types(driver):
    """Query distinct entry types with counts from lifestream."""
    if not driver:
        return None
    try:
        with driver.session(database=ENTRY_DATABASE) as session:
            result = session.run(
                "MATCH (s:StreamEntry) "
                "RETURN s.type AS type, count(s) AS count "
                "ORDER BY count DESC"
            )
            return [{"type": r["type"], "count": r["count"]} for r in result]
    except Exception:
        return None


def _query_base_labels(driver, database):
    """Query base node labels with counts, properties, and common additional labels.

    Groups by base label (single-label nodes) rather than showing every
    label combination separately. Much more readable for reference docs.
    """
    if not driver:
        return None
    try:
        labels_data = {}
        with driver.session(database=database) as session:
            # Get all distinct labels and their counts
            result = session.run(
                "CALL db.labels() YIELD label "
                "CALL { WITH label "
                "  MATCH (n) WHERE label IN labels(n) "
                "  RETURN count(n) AS cnt "
                "} "
                "RETURN label, cnt ORDER BY label"
            )
            for r in result:
                labels_data[r["label"]] = {
                    "count": r["cnt"],
                    "properties": set(),
                    "also_labeled": set(),
                }

            # Get properties per label from schema
            result = session.run(
                "CALL db.schema.nodeTypeProperties() "
                "YIELD nodeType, propertyName "
                "RETURN nodeType, propertyName"
            )
            for r in result:
                prop = r["propertyName"]
                if not prop:
                    continue
                # nodeType is like ":`Agent`" or ":`Agent`:`Person`"
                raw = r["nodeType"]
                # Extract individual labels
                label_parts = [l.strip("` ") for l in raw.split(":") if l.strip("` ")]
                for lbl in label_parts:
                    if lbl in labels_data:
                        labels_data[lbl]["properties"].add(prop)

            # Find common additional labels (co-occurring labels)
            result = session.run(
                "MATCH (n) "
                "WITH labels(n) AS lbls "
                "WHERE size(lbls) > 1 "
                "UNWIND lbls AS base "
                "UNWIND lbls AS other "
                "WITH base, other WHERE base <> other "
                "RETURN base, collect(DISTINCT other) AS co_labels"
            )
            for r in result:
                base = r["base"]
                if base in labels_data:
                    labels_data[base]["also_labeled"] = set(r["co_labels"])

        # Convert sets to sorted lists for output
        for info in labels_data.values():
            info["properties"] = sorted(info["properties"])
            info["also_labeled"] = sorted(info["also_labeled"])

        return labels_data
    except Exception:
        return None


def _query_relationship_properties(driver, database):
    """Query relationship types and their properties."""
    if not driver:
        return None
    try:
        with driver.session(database=database) as session:
            result = session.run(
                "CALL db.schema.relTypeProperties() "
                "YIELD relType, propertyName "
                "RETURN relType, collect(DISTINCT propertyName) AS properties "
                "ORDER BY relType"
            )
            rels = {}
            for r in result:
                # relType looks like ":`REL_TYPE`" -- extract
                rel_type = r["relType"].strip(":` ")
                props = [p for p in r["properties"] if p]
                rels[rel_type] = props
            return rels
    except Exception:
        return None


def _query_indexes(driver, database):
    """Query current indexes."""
    if not driver:
        return None
    try:
        with driver.session(database=database) as session:
            result = session.run(
                "SHOW INDEXES YIELD name, type, labelsOrTypes, properties "
                "WHERE type <> 'LOOKUP' "
                "RETURN name, type, labelsOrTypes, properties "
                "ORDER BY name"
            )
            indexes = []
            for r in result:
                indexes.append({
                    "name": r["name"],
                    "type": r["type"],
                    "labels": ", ".join(r["labelsOrTypes"] or []),
                    "properties": ", ".join(r["properties"] or []),
                })
            return indexes
    except Exception:
        return None


def _query_triggers(driver, database):
    """Query APOC trigger names."""
    if not driver:
        return None
    try:
        with driver.session(database=database) as session:
            result = session.run("CALL apoc.trigger.list() YIELD name RETURN name ORDER BY name")
            return [r["name"] for r in result]
    except Exception:
        return None


def _query_neo4j_version(driver):
    """Query Neo4j version and component info."""
    if not driver:
        return None
    try:
        info = {}
        with driver.session(database="system") as session:
            result = session.run(
                "CALL dbms.components() YIELD name, versions, edition "
                "RETURN name, versions[0] AS version, edition"
            )
            record = result.single()
            if record:
                info["Neo4j"] = f"{record['version']} {record['edition']}"

        # APOC version
        try:
            with driver.session(database=GRAPH_DATABASE) as session:
                result = session.run("RETURN apoc.version() AS v")
                record = result.single()
                if record:
                    info["APOC"] = record["v"]
        except Exception:
            pass

        # GDS version
        try:
            with driver.session(database=GRAPH_DATABASE) as session:
                result = session.run("RETURN gds.version() AS v")
                record = result.single()
                if record:
                    info["GDS"] = record["v"]
        except Exception:
            pass

        return info if info else None
    except Exception:
        return None


# -- Subprocess entry point (fallback -- normally runs in-process) --
if __name__ == "__main__":
    from lib.io import load_params, output
    from lib.db import get_neo4j_driver
    p = load_params()
    drv = get_neo4j_driver()
    try:
        result = sync_system_docs_impl(**p, driver=drv)
        output(result)
    finally:
        drv.close()
